# Cloudflare Pages configuration
name = "windycloud-website"
compatibility_date = "2026-03-20"

[build]
command = "npm run build"
cwd = "/"
watch_dir = "src"

[build.upload]
format = "service-worker"
dir = "dist"
